### ISSUE TITLE
Obj features and a runtime error

### ISSUE THREAD

**Issue by TommeyChang** [ZhuFengdaaa/MG-AuxRN#2]
How can I get the obj feature?

And when I tried the speaker.bash, a runtime error was raised.

Traceback (most recent call last):
  File "r2r_src/train.py", line 572, in <module>
    train_val()
  File "r2r_src/train.py", line 472, in train_val
    train_speaker(train_env, tok, args.iters, val_envs=val_envs)
  File "r2r_src/train.py", line 93, in train_speaker
    speaker.train(interval)   # Train interval iters
  File "/home/ct/Desktop/MG-AuxRN/r2r_src/speaker.py", line 54, in train
    loss = self.teacher_forcing(train=True)
  File "/home/ct/Desktop/MG-AuxRN/r2r_src/speaker.py", line 227, in teacher_forcing
    ctx = self.encoder(can_feats, img_feats, lengths)
  File "/home/ct/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ct/Desktop/MG-AuxRN/r2r_src/model.py", line 513, in forward
    feature.view(batch_size * max_length, -1, self.feature_size),        # (batch, length, # of images, feature_size) --> (batch x length, # of images, feature_size)
RuntimeError: shape '[448, -1, 2176]' is invalid for input of size 548352

**Comment by ZhuFengdaaa** [comment]
The object feature can be downloaded here: 
https://drive.google.com/drive/folders/1u5cSqFOKaleQWc9puv3hzRPqKLi43R_c?usp=sharing

**Comment by cahinostroza** [comment]
Hi @ZhuFengdaaa, i already downloaded the object features, but i have the same problem that @TommeyChang has.
Do u know how could i fix it?

VOCAB_SIZE 992
BIDIR in speaker encoder!!
Traceback (most recent call last):
  File "r2r_src/train.py", line 572, in <module>
    train_val()
  File "r2r_src/train.py", line 472, in train_val
    train_speaker(train_env, tok, args.iters, val_envs=val_envs)
  File "r2r_src/train.py", line 93, in train_speaker
    speaker.train(interval)   # Train interval iters
  File "/content/gdrive/My Drive/U/9° Semestre/Magister/R2R-EnvDrop/r2r_src/speaker.py", line 54, in train
    loss = self.teacher_forcing(train=True)
  File "/content/gdrive/My Drive/U/9° Semestre/Magister/R2R-EnvDrop/r2r_src/speaker.py", line 227, in teacher_forcing
    ctx = self.encoder(can_feats, img_feats, lengths)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/gdrive/My Drive/U/9° Semestre/Magister/R2R-EnvDrop/r2r_src/model.py", line 512, in forward
    feature.view(batch_size * max_length, -1, self.feature_size),        # (batch, length, # of images, feature_size) --> (batch x length, # of images, feature_size)
RuntimeError: shape '[448, -1, 2176]' is invalid for input of size 548352

**Comment by TommeyChang** [comment]
It seems that it is caused by the function 'from_shortest_path' in speaker.py.

@cahinostroza You can try to remove the index 2 in this line: img_feats.append(self.listener._feature_variable(obs)[2])
